### ISSUE TITLE
Feature request - Suspend/Resume schedule with input

### ISSUE THREAD

**Issue by scambo00** [biddster/node-red-contrib-schedex#14]
Programmable input to suspend or resume schedule.

**Comment by biddster** [comment]
Could you please flesh this out a little more? I'm not sure what you need.

**Comment by scambo00** [comment]
For the check box "Suspending scheduling"  could an input be added to make this programmable?  I am looking to have several different schedules in the same flow.  I need a way to suspend them all with an input.  Without having to open each and check the box.

**Comment by biddster** [comment]
Ok - this sounds reasonable, I'll add it to a future release.

**Comment by biddster** [comment]
This is in testing at the moment, should be released next week.

**Comment by elyobelyob** [comment]
Any news on this? it's something I'm eagerly waiting for! Thanks

**Comment by biddster** [comment]
Fixed in release 0.8.0, please see the readme for details of programmatic control.

**Comment by elyobelyob** [comment]
Thankyou
