### ISSUE TITLE
Future request: Schedule On time / Of time received via input

### ISSUE THREAD

**Issue by jroux1** [biddster/node-red-contrib-schedex#15]
Hi, I need a scheduler where the on/off time can be injected via the input, maybe variable names:
- msg.payload.ontime 
- msg.payload.offtime

I want to store the variables in a file, and be able to change them via the node red dashboard UI. Then, with an event feed them into your node, for your node to save the on and off times, until another feed of different times, for your node to then trigger events.

Is this something you would want to add to your node?

**Comment by biddster** [comment]
Yeah - I'll consider this. I think that increasingly, being able to configure via an event will be useful for recomposition within UI outside of the standard NR dash.

**Comment by biddster** [comment]
This is in testing at the moment, should be released next week.

**Comment by siburny** [comment]
It would great if we were able to adjust on/off offset as well.
Example: I want my entrance lights to come on at sunset. If it's not sunny, I would want to adjust offset of "on" event by 30 minutes or so.

**Comment by vielleicht** [comment]
This would be a very interesting feature for me too. It would help me to implement a variable buzzer, which can be set by an UI.

**Comment by biddster** [comment]
Fixed in release 0.8.0
