### ISSUE TITLE
Off issues when using offset

### ISSUE THREAD

**Issue by elyobelyob** [biddster/node-red-contrib-schedex#17]
I seem to get issues of things not switching off when I enter an offset. If the offset is set, but the checkbox for "use random" is not set, then no message is sent. Therefore my light stays on.

**Comment by biddster** [comment]
Thanks for the report, what version of schedex are you using?

**Comment by elyobelyob** [comment]
0.80 ..

**Comment by elyobelyob** [comment]
Anything with an offset doesn't seem to send a payload through. I'm checking every 24 hours, and having to manually switch lights off. Hopefully all now set to zero offset and will know in 24 hours whether that's fixed the lounge light. Other lights with zero offsets seem to be working fine.

**Comment by elyobelyob** [comment]
I'm using the programmatic control, if that helps.

**Comment by biddster** [comment]
Yeah, that does help. The programmatic control is new so it's perfectly possible there are issues. I don't actually use it myself.

**Comment by biddster** [comment]
I've not managed to recreate it yet. I'll post my test scenario later.

**Comment by elyobelyob** [comment]
`[{"id":"f07efcf4.c89b9","type":"function","z":"16e83b76.fb2c85","name":"Create msg","func":"msg.topic = msg.topic + msg.payload;\n\nreturn msg;","outputs":"1","noerr":0,"x":470,"y":340,"wires":[["edabe00.4deb62","1b3e9c20.fd7924"]]},{"id":"8d0bc1d4.c0ee2","type":"change","z":"16e83b76.fb2c85","name":"","rules":[{"t":"change","p":"payload","pt":"msg","from":"status/holiday/off/","fromt":"str","to":"suspended true","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"status/holiday/on/","fromt":"str","to":"suspended false","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":300,"y":240,"wires":[["1ae15cf1.7e57d3"]]},{"id":"c652051d.b3e848","type":"template","z":"16e83b76.fb2c85","name":"Set Payload","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"status/holiday/on/","x":210,"y":200,"wires":[["8d0bc1d4.c0ee2"]]},{"id":"edabe00.4deb62","type":"mqtt out","z":"16e83b76.fb2c85","name":"","topic":"","qos":"","retain":"","broker":"4b45562f.af8f38","x":610,"y":380,"wires":[]},{"id":"1b3e9c20.fd7924","type":"debug","z":"16e83b76.fb2c85","name":"","active":true,"console":"false","complete":"true","x":610,"y":440,"wires":[]},{"id":"e7ce5786.2748d8","type":"inject","z":"16e83b76.fb2c85","name":"","topic":"","payload":"","payloadType":"date","repeat":"60","crontab":"","once":true,"x":130,"y":160,"wires":[["c652051d.b3e848"]]},{"id":"1ae15cf1.7e57d3","type":"schedex","z":"16e83b76.fb2c85","name":"TV Light","suspended":false,"lat":"51.3","lon":"0.3","ontime":"02:54","ontopic":"action/telldus/onOffDevice/669968/","onpayload":"1","onoffset":"0","onrandomoffset":0,"offtime":"02:55","offtopic":"action/telldus/onOffDevice/669968/","offpayload":"0","offoffset":"2","offrandomoffset":0,"x":380,"y":280,"wires":[["f07efcf4.c89b9"]]},{"id":"4b45562f.af8f38","type":"mqtt-broker","z":"","broker":"localhost","port":"1883","clientid":"","usetls":false,"verifyservercert":true,"compatmode":true,"keepalive":"15","cleansession":true,"willTopic":"","willQos":"0","willRetain":null,"willPayload":"","birthTopic":"","birthQos":"0","birthRetain":null,"birthPayload":""}]`

**Comment by elyobelyob** [comment]
There's a ripped down copy of my code. Just tested and it doesn't switch the light off, but does turn on. Hope that helps. (0.16.2 of node-red as well).

**Comment by biddster** [comment]
Think I've found it, although there are several issues that need to be addressed.

1. When schedex receives an input schedule instruction it initially tries to work out if the on and off times are in the future. This calculation wasn't taking into account the offset. 
1. I hadn't considered that schedex might receive input schedule instructions at the same frequency as the internal timer (i.e. in your example, every minute)
1. Schedex doesn't currently check to see if the input schedule instructions mutate the state and blindly reschedules. 

So in your example. You send an input schedule instruction every minute. Every minute schedex re-evaluates the schedule. At the on time, schedex re-evaluates and determines that the time is in the past and adds one day, before adding the offset. Hence why it works when the offset is 0.

**Comment by biddster** [comment]
I've released 0.8.1. Not had the usual soak testing I've done in the past but it's a relatively small change.

**Comment by elyobelyob** [comment]
Unfortunately, I am unable to get this to work. I am running 0.8.1, and have rebooted my system since upgrading.

**Comment by elyobelyob** [comment]
Nope, I gave it more testing, and it seems to work like a charm. Apologies!

**Comment by biddster** [comment]
Glad it's working. You have to use --save to get npm packages add to package.json.
