### ISSUE TITLE
date missmatch when time + offset exceeds midnight

### ISSUE THREAD

**Issue by steviedv** [biddster/node-red-contrib-schedex#24]
Example:
Schedule: Fr, Sa
On time: sunset
Offset: 0

Off time: 23:00
Offset: 120

result:
ON 2017-08-12 20:46  (Sa)
OF 2017-08-18 01:00 (Fr next week)

**Comment by biddster** [comment]
Many thanks for the report. I'll look into it.

**Comment by biddster** [comment]
What version of schedex are you using @steviedv ?

**Comment by steviedv** [comment]
biddster,
 I am using 1.0.0,
 steviedv.

![image](https://user-images.githubusercontent.com/30941054/33647485-8eb59562-da55-11e7-9a3c-9a913c788b87.png)

**Comment by biddster** [comment]
Fixed in 1.1.1.
