### ISSUE TITLE
Specific date and time

### ISSUE THREAD

**Issue by mikebiddell** [biddster/node-red-contrib-schedex#25]
Any chance of an output as per above ????

**Comment by biddster** [comment]
When you say specific date and time, what are the requirements?

Emit a message just once on a specific date and time? E.g. 2017/12/25 09:00. After that, you'd expect to redeploy the node with config for the next year?

**Comment by biddster** [comment]
BTW - there is https://github.com/chameleonbr/node-red-contrib-cron

For example of configuring it, see here https://crontab.guru/#0_10_25_12_*

**Comment by mikebiddell** [comment]
Google
it needs to be recurring or non-recurring....... like a birthday or MOT (recurring) or just one specific day like a doctor's appointment (non-recurring). Or is that too hard ? If it is, a one shot (non-recurring) which you can re-schedule manually would be a start.
Dad
    On Friday, November 24, 2017, 11:39:15 PM GMT, biddster <notifications@github.com> wrote:  
 
 
When you say specific date and time, what are the requirements?

Emit a message just once on a specific date and time? E.g. 2017/12/25 09:00. After that, you'd expect to redeploy the node with config for the next year?

**Comment by biddster** [comment]
You can easily do that with https://github.com/chameleonbr/node-red-contrib-cron

**Comment by mikebiddell** [comment]
didn't realise..... I'll try it.
    On Saturday, November 25, 2017, 9:57:31 AM GMT, biddster <notifications@github.com> wrote:  
 
 
You can easily do that with https://github.com/chameleonbr/node-red-contrib-cron

**Comment by biddster** [comment]
https://flows.nodered.org/node/node-red-node-google
