### ISSUE TITLE
Set days (on the schedule) programmatically

### ISSUE THREAD

**Issue by younesmaia** [biddster/node-red-contrib-schedex#27]
A nice addition would be to provide the day of the week over msg.payload and a true/false argument, in order to enable/disable the schedule that day.

Eg: 
msg.payload.monday = true

If a day of the week is not defined on the object, the node should default to what's set on the configuration.

**Comment by bvanev** [comment]
This would also be very useful for me.  This would permit the offline storage of a daily schedule in either a config file or database.

**Comment by biddster** [comment]
Fixed in release 1.2.0
