### ISSUE TITLE
Getting on and off times in local time

### ISSUE THREAD

**Issue by drmibell** [biddster/node-red-contrib-schedex#28]
Formatting times with toUTCString on an info request is a good idea, but it would be nice to have the option of getting local time or the unix time. The UTC string does not seem to be ingested by the moment library, so conversions are difficult.

**Comment by elyobelyob** [comment]
Is there a good reason to raise this on the moment project? Sounds
reasonable to me.

**Comment by elyobelyob** [comment]
Seems a discussion already had ... http://momentjs.com/docs/#/parsing/utc/

**Comment by drmibell** [comment]
Thanks for looking into this. I share your preference for ISO 8601 format, in general and on principle, but here it seems odd that after entering local On and Off times, the `info` command returns them as ISO. I like the idea of an `info_local` command. My first thought was an option (checkbox) in the edit dialog requesting reports as local time, but it's not clear where to put it or how to word the label.

**Comment by sam-wright** [comment]
A checkbox that says "use localtime" or something equivalent would be _greatly_ appreciated. I ran in circles for a long time wondering why events weren't firing before I realized the times were in GMT

**Comment by sam-wright** [comment]
ah please disregard my comment, I simply didn't pass localtime to my container. What I was talking about is not related to this discussion.

**Comment by biddster** [comment]
`info_local` command available in 1.6.0
