### ISSUE TITLE
Feature request: programmatic control of location

### ISSUE THREAD

**Issue by drmibell** [biddster/node-red-contrib-schedex#31]
Would it be possible to set the location (latitude and longitude) from a message? I would like to be able to deploy flows with several schedex nodes to a number of users in various locations, without giving them access to the editor. The timer settings are read from a file that the user can edit, and it would be helpful to be able to do the same with the location. From my not-so-expert reading of the code, it seems that the node tries to obtain the geolocation of the host. This would solve the problem, but does not seem to be working.

**Comment by biddster** [comment]
Fixed in release 1.2.0
