### ISSUE TITLE
Passthrough msg object

### ISSUE THREAD

**Issue by kenci** [biddster/node-red-contrib-schedex#37]
Is it possible to passtrough the msg object? I need the initial msg.topic to identify an element,

**Comment by biddster** [comment]
It's not currently possible, but it could be, assuming I've understood what you need.

When schedex is triggered via an input message (rather than a schedule) you want the incoming message topic to  override the configuration in the node?

**Comment by drmibell** [comment]
I would like to see an almost complete passthrough option available, presumably via a checkbox. I think the only cases where it is not possible to pass through the incoming message would be where `msg.payload` is equal to "on", "off", "toggle", or "info".

**Comment by biddster** [comment]
Ok, @drmibell, so any input message to schedex that isn't explicitly handled by Schedex should be emitted if the passthrough checkbox is ticked?

**Comment by drmibell** [comment]
Yes, that was my suggestion. I have ideas for flows where this would be useful. Do you see any difficulties?

**Comment by biddster** [comment]
I think this should be pretty trivial. I have a fix in soak for #56 so once I'm happy with that I'll start thinking about this.

**Comment by biddster** [comment]
I've got this on test here are home. Should release it this week.

**Comment by biddster** [comment]
Fixed in 1.9.0
