### ISSUE TITLE
Undesired information generated by msg.payload = info

### ISSUE THREAD

**Issue by aiot-maker** [biddster/node-red-contrib-schedex#44]
Using schedex contrib node on windows10, Node.js v8.11.1, Node-RED v0.20.0

Feeding the node with msg.payload = info results the node displaying in the debug panel its properties as well as the object _.flow, which is huge and disclose information of all nodes in all flows. I understand such information is not relevant to schedex and should not leak.

![i-01](https://user-images.githubusercontent.com/38989199/54397457-48fb2200-4695-11e9-8383-da3bef59a469.png)

**Comment by drmibell** [comment]
I am seeing this in v1.5.0 but not in v1.4.1, so I suspect the behavior was introduced while trying to get the `info` command to produce the complete configuration.

**Comment by biddster** [comment]
Thanks for the report, I'll issue a fix.

**Comment by biddster** [comment]
Fixed in 1.5.1
