### ISSUE TITLE
Inconsistent results from msg.payload = 'info'

### ISSUE THREAD

**Issue by drmibell** [biddster/node-red-contrib-schedex#46]
When interrogated using `msg.payload = 'info'`, the `onrandomoffset` and `offrandomoffset` properties are not consistent in how they report their state. When active they report a boolean `true` value, but when inactive they report a numerical value of `0`. There are obvious workarounds, but it would be preferable if the "false" value were actually boolean `false`.

**Comment by biddster** [comment]
Thanks for the report, I'll look into it.

**Comment by biddster** [comment]
Fixed in 1.6.0
