### ISSUE TITLE
Feature request: node name in msg.payload = 'info' output

### ISSUE THREAD

**Issue by drmibell** [biddster/node-red-contrib-schedex#47]
It would be very helpful to include the name of the `schedex` node in the object sent in response to a `msg.payload = 'info'` request. I sometimes send an 'info' request to several `schedex` nodes at once, and would like to be able to process the responses in a single flow instead of essentially having to duplicate that flow for each node.

**Comment by biddster** [comment]
Fixed in 1.6.0

**Comment by drmibell** [comment]
Did not want to open a new issue, but v1.6.0 seems to be on npm but not picked up by the NR flows library.
