### ISSUE TITLE
Schedex ~30-50 sec delay 

### ISSUE THREAD

**Issue by myozone** [biddster/node-red-contrib-schedex#52]
Schedex has an about ~30-40 sec delay on it's times. I set it for say 22:00 and it triggers anything from about 30-50 seconds late on both on and off. Incidentally the PI date/time is spot on. Putting a debug on it's output shows the delayed time. (Another type of timer node works ok it's only schedex)

**Comment by biddster** [comment]
Excellent spot, I've recreated it. Many thanks.

**Comment by biddster** [comment]
Fix released in 1.6.1

**Comment by gerhard1951** [comment]
Using the latest releases I still or again observe the same problem with Schedex: After a reboot of the Raspi its system time is correct, but Schedex switches 30 to 50 seconds later than scheduled. 
How to solve this?
Thanks
Gerhard
