### ISSUE TITLE
Sunrise/Sunset question

### ISSUE THREAD

**Issue by bizit524** [biddster/node-red-contrib-schedex#53]
Hello. 
Great node, use it for tons of flows. I had a question thought about the sunrise/sunset aspect. I am able to set the on off action based on the sunrise/sunset options. This is great. However is there a way to trigger on the sunrise/sunset and THEN in the on/off payloads send the sunrise/sunset time? 
What I have been doing is having a function afterwards that triggers a timestamp then sends it down the flow but it would be nice to forgo that option and just send the sunset/sunrise times in the payload. Maybe it's an option I am missing like $sunrise? or something

**Comment by biddster** [comment]
If you send an input payload of `info` or `info_local`, schedex will emit a payload that contains the on/off times. So if your schedex node is on at sunset, the time in the `info` payload will be sunset. 

Check out the readme for more info.

**Comment by bizit524** [comment]
that is perfect! I didn't even think of that duh! i do info but forgot I could parse the output
