### ISSUE TITLE
offoffset not working in 1.6.4?

### ISSUE THREAD

**Issue by bjoernbusch** [biddster/node-red-contrib-schedex#61]
I updated to 1.6.4 yesterday and now the offoffset parameter is not working anymore.

I have a simple schedex configured to turn off at dusk. I do some calculation in a function before the schedex and then send a offoffset to the schedex, which was working fine so far. I always sent it like this:

msg.payload =
{ 
    offoffset: diff
};

The diff is properly calculated, but the shown time doesn't change. Any hints on this what might have changed?

**Comment by biddster** [comment]
Regression in 1.6.3. Fixed in 1.6.5.

**Comment by bjoernbusch** [comment]
Awesome, thanks for the quick fix! Can confirm it works again.
