### ISSUE TITLE
Get the overall state?

### ISSUE THREAD

**Issue by ingo-b** [biddster/node-red-contrib-schedex#63]
After sending "info" the emitted object contains "state". This state shows the state of the timer, not the overall state which would also consider the manual on/off mode. Is it possible to get the overall state?

**Comment by biddster** [comment]
Yes, I think this is possible.

**Comment by biddster** [comment]
I"m looking at this now. I think I will include a property called actuatedstate which will indicate the last state that was actuated, either by a manual event or scheduled event. 

The only thing I'm undecided upon is the initial value of the property. Currently it's null if nothing has happened. I think that's the correct thing to do, but I'm open to suggestions.

**Comment by biddster** [comment]
Fixed in 1.10.0
