### ISSUE TITLE
Doesn`t send progrmatic set events

### ISSUE THREAD

**Issue by amizer12** [biddster/node-red-contrib-schedex#66]
Hi,
Not sure if i`m doing something wrong or is there an issue with the node.
I`m using UI input to set the on and of time ( i want 24 hours timer ).
After some initial formating this is what is actually being passed over into schedex and in admin gui you i can see that my on and of time are being set - BUT - nothing is actually happening at those times - just like the timer wouldn`t work at all.

My Flow:
![image](https://user-images.githubusercontent.com/55321188/71372575-1469ae80-25b5-11ea-9822-9599650308cb.png)
Data accepted as ontime by Schedex:
![image](https://user-images.githubusercontent.com/55321188/71372605-28adab80-25b5-11ea-887a-c53665f93919.png)

When i inject manually ON or OFF Schedex sends out the specified payloads, but nothing is happening when i set the time either programatically or even manually via the node configuration as well.
Alsoo  interesting thing is that when it trigger the "Info" payload to read properties of Schedex i`m getting following error:
![image](https://user-images.githubusercontent.com/55321188/71374852-898cb200-25bc-11ea-9322-978dab3025c1.png)

Any idea what i could be doing wrong ?

**Comment by biddster** [comment]
Sorry for the delay, I'll try to recreate it from here. I'm not sure what the problem yet.

**Comment by biddster** [comment]
So there's a bug in Schedex with the info command where you don't set and end time. I'll fix that. Not sure about your other issue yet.

**Comment by biddster** [comment]
I've not recreated the issue where nothing is sent. I have a similar setup in my flow and it's working fine.

**Comment by biddster** [comment]
I've released 1.8.1 with a fix for the info command.
