### ISSUE TITLE
Nadir Offsets

### ISSUE THREAD

**Issue by Wordna1** [biddster/node-red-contrib-schedex#76]
I am trying to trigger a NodeRED flow 3 hours before Nadir which is currently at approximately 00:47.  I seem to be able to offset until midnight (roughly -47), but offsetting to 3hrs earlier (ie. -180) yields a "Failed to find valid time [nadir]" error message.

**Comment by biddster** [comment]
Confirmed, thanks for the report. I'll work up a fix.

**Comment by biddster** [comment]
Fixed in 1.10.2

**Comment by Wordna1** [comment]
Thank you!
