### ISSUE TITLE
schedex using utc and  not using system date

### ISSUE THREAD

**Issue by benpoe** [biddster/node-red-contrib-schedex#83]
i was wondering why my wake up lights didn't work and found out that schedex does not seem to be using system date. IE, it's not honouring the offfset and only uses utc time. and due to winter saving time i'd need to offset my times with 1 hour.

**Comment by benganellison** [comment]
@benpoe, why did you close this issue? i have the same issue. did you find the reason?

**Comment by benganellison** [comment]
for information: i just found the reason to why i had problems. i had a 60 offset. i did copy another node and didn't modify it fully for my new needs
